name: Build and Push Docker Image to DockerHub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:latest

      - name: Run container and show logs
        run: |
          docker run -d --name qr-generator -p 8501:8080 ${{ secrets.DOCKERHUB_USERNAME }}/qr-code-generator-app:latest
          sleep 5
          docker logs qr-generator

      - name: Test QR endpoint
        run: |
          RESPONSE=$(curl -s -o qr_test.png -w "%{http_code}" "http://localhost:8501/generate?url=https://example.com")
          if [ "$RESPONSE" -ne 200 ]; then
            echo "QR generation failed with status $RESPONSE"
            exit 1
          fi
          echo "QR generated successfully"
          ls -l qr_test.png
